name: Discussions to markdown

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

  discussion:
    types: [created, edited, deleted]

env:
    GH_TOKEN: ${{ secrets.DISCUSSIONS_AUTOMATION }}
    ORGANIZATION: "devopslearninglab" #$GITHUB_REPOSITORY_OWNER
    REPO: "change-log" #$GITHUB_REPOSITORY
    CATEGORY: "DIC_kwDOHsO2_M4CQVw_"

jobs:
  discussion-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: List discussions
        id: list-discussions
        run: |
          gh api graphql -f query='query ListDiscussionsByCategory {
            repository(owner: "devopslearninglab", name: "change-log") {
                discussions(first: 50, categoryId:"DIC_kwDOHsO2_M4CQVw_"){
                    totalCount
                    pageInfo {
                        # type: PageInfo (from the public schema)
                        startCursor
                        endCursor
                        hasNextPage
                        hasPreviousPage
                    }
                    edges {
                        cursor
                        node{
                            id
                            title
                            bodyHTML
                            author{
                                login
                            }
                            answerChosenAt
                            category{
                                id
                                name
                                description
                                isAnswerable
                                slug
                                createdAt
                                updatedAt
                            }
                        } 
                    }
                }
            }
          }' > ${{ env.CATEGORY }}.json
