name: Discussions to markdown

on:
  push:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

  # created, edited, deleted, transferred, pinned, unpinned
  # labeled, unlabeled, locked, unlocked, category_changed, answered, unanswered
  # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#discussion
  discussion:
    types: [created, edited, deleted]

env:
    GH_TOKEN: ${{ secrets.DISCUSSIONS_AUTOMATION }}
    ORGANIZATION: "devopslearninglab" #$GITHUB_REPOSITORY_OWNER
    REPO: "change-log" #$GITHUB_REPOSITORY
    CATEGORY: "DIC_kwDOHsO2_M4CQVw_"

jobs:
  discussion-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: List discussions entries by category
        id: list-discussions-by-category
        run: |
          gh api graphql -f query='query ListDiscussionsByCategory {
            repository(owner: "devopslearninglab", name: "change-log") {
                discussions(first: 50, categoryId:"DIC_kwDOHsO2_M4CQVw_"){
                    totalCount
                    pageInfo {
                        # type: PageInfo (from the public schema)
                        startCursor
                        endCursor
                        hasNextPage
                        hasPreviousPage
                    }
                    edges {
                        cursor
                        node{
                            id
                            title
                            body
                            bodyText
                            bodyHTML
                            author{
                                login
                            }
                            answerChosenAt
                            category{
                                id
                                name
                                description
                                isAnswerable
                                slug
                                createdAt
                                updatedAt
                            }
                        } 
                    }
                }
            }
          }' > ${{ env.CATEGORY }}.json

      - name: Archive discussion entries
        uses: actions/upload-artifact@v3
        with:
          name: discussion-entries
          path: ${{ env.CATEGORY }}.json

      - name: Print discussion entries
        shell: bash
        run: |
          value=`cat ${{ env.CATEGORY }}.json`
          echo $value
      
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          commit_author: Author <actions@github.com>
          commit_user_email: actions@github.com
          commit_message: Apply automatic changes
          branch: main
          output_file_paths: '[./change-log-entries-test.md]'
          categories: '[json-to-html-table]'
